# .streamlit/secrets.toml

[mysql]
host = "setjetters1.c2ipvnggy6hj.us-east-2.rds.amazonaws.com"
database = "setjetters_export"
user = "admin"
password = "NumberSheep"

[opencage]
api_key = "3b69750e31b941a1aeb0deb27a044ec0"
